### ISSUE TITLE
Bobo's diet plan doesn't work

### ISSUE THREAD

**Issue by Kennethrvr** [ig-ealbert/bobos-big-adventure#1]
Bobo become the king in the north or not?
il waiting part 2 <3

**Comment by ig-ealbert** [comment]
BoBo's diet plan does work!  She stops eating 🌲 , 🏢 , 🚗 , and she does revert to her housecat size!

If this diet is not working for you, I would recommend avoiding all inorganic materials.

BoBo is queen of the cat bed at the end of the story. 😸
